Banned:
  - ARROW_DAMAGE
  - ARROW_FIRE
  - ARROW_INFINITE
  - ARROW_KNOCKBACK
  - DAMAGE_ALL
  - DAMAGE_ARTHROPODS
  - DAMAGE_UNDEAD
  - FIRE_ASPECT
  - KNOCKBACK
  - PROTECTION_ENVIRONMENTAL
  - PROTECTION_FALL
  - PROTECTION_FIRE
  - PROTECTION_PROJECTILE