banned:
  - ARROW_DAMAGE
  - ARROW_FIRE
  - ARROW_INFINITE
  - ARROW_KNOCKBACK
  - DAMAGE_ALL
  - FIRE_ASPECT
  - KNOCKBACK
  - PROTECTION_ENVIRONMENTAL
  - PROTECTION_FALL
  - PROTECTION_FIRE
  - PROTECTION_PROJECTILE
  - PROTECTION_EXPLOSIONS
  - THORNS
message: "You cannot do that!"